# Generated by Django 2.2.6 on 2019-10-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='category',
            new_name='confidence',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='title',
            new_name='label',
        ),
    ]
