# Generated by Django 2.2.6 on 2019-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20191005_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='score',
        ),
        migrations.AddField(
            model_name='object',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
