# Generated by Django 2.2.6 on 2019-10-06 00:25

from django.db import migrations, models
import wrappr_backend.detection.models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20191005_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='score',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(null=True, upload_to=wrappr_backend.detection.models.result_path),
        ),
    ]
