# Generated by Django 2.2.6 on 2019-10-06 00:26

from django.db import migrations, models
import wrappr_backend.detection.models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20191006_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='height',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='width',
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(upload_to=wrappr_backend.detection.models.frame_path),
        ),
    ]
