# Generated by Django 2.2.6 on 2019-10-06 01:05

from django.db import migrations, models
import wrappr_backend.detection.models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20191006_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='confidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=wrappr_backend.detection.models.result_path),
        ),
    ]
